name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        # dotnet-version: 3.1.301
    - name: Install tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet restore
    - name: Build using FAKE
      #run: dotnet fake build
      run: bc.cmd
    # - name: Build
    #  run: dotnet build --configuration Release --no-restore
    # - name: Test
    #  run: dotnet test ./tests/xpect/xpect.fsproj --verbosity normal
